name: Check Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format
        run: clang-format --dry-run --Werror include/keychain/*.h src/*.cpp
